version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongo-network

  mongo-compass:
    image: mongo-express
    container_name: mongo-compass
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - mongo-network

  mongo-atlas:
    image: mongodb/atlas
    container_name: mongo-atlas
    environment:
    stdin_open: true # Enable reading from the standard input
    tty: true # Allocate a pseudo-TTY
    ports:
      - "8080:8081"
    command: /bin/bash

networks:
  mongo-network:
    driver: bridge
